version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/secretlab
file_exists_behavior: OVERWRITE
permissions: 
 - object: /var/www/html/secretlab
   owner: ec2-user
   group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/change_ownership.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/deploy_laravel.sh
      timeout: 300  
      runas: ec2-user
    - location: scripts/change_laravel_folder_permissions.sh
      timeout: 300  
      runas: ec2-user